version: '3.3'

volumes:
  anonymous_valentine_postgres_data:

services:
  postgres:
    container_name: anonymous-valentine-postgres
    image: postgres:13.10
    env_file: .environment
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bot:
    container_name: anonymous-valentine-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .environment
    depends_on:
      - postgres
    volumes:
      - .:/app