version: '3.3'

volumes:
  anonymous_valentine_postgres_data:

services:
  postgres:
    container_name: anonymous-valentine-postgres
    image: postgres:13.10
    env_file: .environment
    ports:
      - 6433:5432
    volumes:
      - anonymous_valentine_postgres_data:/var/lib/postgresql/data

  bot:
    container_name: anonymous-valentine-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .environment
    depends_on:
      - postgres
