"""empty message

Revision ID: 759aaa6ffc3c
Revises:
Create Date: 2025-02-09 15:53:05.651962

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from models.messages import MessageContentTypeChoices, MessagePrivacyTypeChoices


# revision identifiers, used by Alembic.
revision: str = '759aaa6ffc3c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'compliments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('text'),
    )
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=True),
        sa.Column('recipient_id', sa.Integer(), nullable=True),
        sa.Column(
            'privacy_type',
            sqlalchemy_utils.types.choice.ChoiceType(
                choices=MessagePrivacyTypeChoices.choices(), impl=sa.String(length=9)
            ),
        ),
        sa.Column(
            'content_type',
            sqlalchemy_utils.types.choice.ChoiceType(
                choices=MessageContentTypeChoices.choices(), impl=sa.String(length=9)
            ),
        ),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('telegram_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('messages')
    op.drop_table('compliments')
    # ### end Alembic commands ###
