"""empty message

Revision ID: 7c1c2832f1e8
Revises: 759aaa6ffc3c
Create Date: 2026-02-12 05:58:53.917348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1c2832f1e8'
down_revision: Union[str, None] = '759aaa6ffc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='compliments_pkey'),
    sa.UniqueConstraint('text', name='compliments_text_key')
    )
    # ### end Alembic commands ###
