INSERT INTO compliments (text) VALUES ('Даже когда я не вижу тебя, я знаю, что ты выглядишь потрясающе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Каждый раз не могу дождаться, когда снова тебя увижу.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('В тебе есть всё, чего мог бы пожелать любой мужчина.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Надеюсь, тебе так же хорошо со мной, как мне всегда хорошо с тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне хочется проводить с тобой всё своё время.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я бы пошел за тобой куда угодно.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне так нравится твой стиль!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('От тебя у меня захватывает дух.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты удивительный и прекрасный человек.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Без тебя я не был бы тем, кто я есть.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я так рад, что в твоём сердце есть место для меня.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Не знаю, как бы справлялся со всем без твоей поддержки.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я чувствую, как ты меняешь мой мир к лучшему каждый день.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я так ценю твоё доверие!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твои советы — самые важные для меня, они всегда мне помогают.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты даже не представляешь, сколько значишь для меня!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я очень ценю нашу с тобой удивительную связь.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я хочу всегда быть только твоим.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты помогаешь мне стать лучше.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Если бы я знал, что сегодня последний день моей жизни, я хотел бы провести его только с тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — моя родственная душа.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мир без тебя был бы пустым и бессмысленным.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Когда я смотрю на тебя, мне тяжело поверить, как же мне повезло.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я даже не знал, что такое любить и быть любимым, пока не встретил тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я думаю о тебе всегда — как только просыпаюсь и когда ложусь спать.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Спасибо за то, что ты пришла в мою жизнь.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне так хорошо с тобой, будто мы знаем друг друга целую вечность.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я понял, что всю жизнь искал именно тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты всегда можешь меня рассмешить.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Воспоминания о тебе греют мою душу.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Спасибо за то, что ты всегда рядом.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Каждый день с тобой для меня как подарок.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты такой интересный человек, мне никогда не надоест тебя изучать.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Спасибо, что ты всегда на моей стороне.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты не только моя любимая девушка, но и мой лучший друг.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Самое удивительное приключение моей жизни — это быть с тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я так люблю обнимать тебя!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я так счастлив, когда ты рядом!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — воплощение моей мечты.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ни у кого нет таких нежных рук, как у тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Самая большая радость — быть с тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты такая чувственная и притягательная!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне нравится в тебе абсолютно всё.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты такой вдумчивый и внимательный человек.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты поражаешь меня своей решительностью и силой духа.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Иногда мне хочется стать тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я считаю, что на таких добрых людях, как ты, держится весь мир.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я всегда могу открыться тебе и знаю, что ты ни за что меня не осудишь.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой я могу быть собой на сто процентов.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('От тебя я каждый день узнаю столько нового и интересного!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я искренне восхищаюсь тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я так уважаю тебя!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твоя уверенность в себе делает тебя ещё очаровательнее.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой в моей жизни всё обретает смысл.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я поражаюсь тому, как потрясающе ты ладишь с людьми!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой я решаюсь на то, что никогда не смог бы сделать без тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я не хочу даже думать о том, что было бы, если бы мы не встретились.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты прекрасна такой, какая есть.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Когда я хочу поделиться сокровенным, первая, о ком я думаю, — это ты.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Рядом с тобой всё становится осмысленным.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты мотивируешь меня быть лучшим.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У тебя безупречный вкус.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты такой честный и справедливый человек!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты очень рассудительная. Я всегда принимаю решения, посоветовавшись с тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты такая лёгкая и искренняя!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — источник вдохновения для всех, кто тебя окружает.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Когда ты заходишь в комнату, ты будто освещаешь её своим сиянием.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Никогда не забывай о том, как ты прекрасна.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Нет ничего приятнее в жизни, чем твой смех.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У тебя такие нежные и изящные руки.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Когда ты улыбаешься, твои глаза просто искрятся.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я обожаю любоваться тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты была бы потрясающей музой для самых лучших художников.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твои грациозные движения меня просто завораживают.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты так мило прищуриваешься, когда улыбаешься, — я не могу отвести взгляд.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У тебя потрясающе царственная осанка и походка.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты прекрасно танцуешь! Наверное, ты где-то училась танцам?') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('От тебя потрясающе пахнет! У тебя такие изысканные духи.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты просто незабываема — я узнал бы тебя в любой толпе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты просто в фантастической форме!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне так нравится, что ты не стесняешься быть такой, какая есть.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я восхищён твоим безупречным вкусом и чувством прекрасного.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты одеваешься очень элегантно.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У тебя незабываемый цвет глаз.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У тебя такие изящные музыкальные пальцы. Ты умеешь играть на каком-то инструменте?') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Никто на свете не сравнится с тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Если бы ты была актрисой, я бы пересмотрел все фильмы с тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я так горжусь тобой!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой мне никогда не бывает скучно.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мой дом — там, где ты.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Каждый раз, прощаясь с тобой, я уже не могу дождаться, чтобы увидеть тебя снова.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С каждой секундой я влюбляюсь в тебя все больше и больше.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Моё сердце принадлежит только тебе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ради тебя я готов на всё.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('День рядом с тобой пролетает как одна секунда.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У меня нет вредных привычек, но ты — моя зависимость, от которой я не могу отказаться.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('В мире не хватит слов, чтобы выразить то, что я к тебе чувствую.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты лучшее, что произошло со мной.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('В тебя невозможно не влюбиться.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я научился любить благодаря тебе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я так ценю, что ты выбрала именно меня!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я так скучаю по тебе, что сплю в обнимку с подушкой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — мой маяк и освещаешь мне путь в темноте.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Для меня ты — само совершенство.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Хочу заботиться о тебе и оберегать тебя всю жизнь.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я чувствую, будто знал тебя в прошлой жизни и там мы были вместе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты заполнила собой все мои мысли.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я мечтаю, чтобы ты никогда не грустила, и всё сделаю для этого.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой мне нравится даже просто молчать, ведь мы понимаем друг друга без слов.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой я стал другим человеком — ты сделала меня лучше.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я принимаю и люблю тебя любой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты всегда можешь мне доверять.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты просто создана для любви и заботы.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У меня от тебя бабочки в животе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я не могу прожить ни дня без твоего любящего взгляда.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне нравится чувствовать твою руку в своей.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты помогаешь мне быть самим собой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Хочу, чтобы наши дети были похожи на тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты просто блистательна!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твоя красота — это просто нечто!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('В тебя невозможно не влюбиться.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты прекрасна и долгожданна, как первое весеннее солнце.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У меня мурашки от твоей красоты!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я вижу твою красоту не только глазами, но и сердцем.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — моя драгоценность.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне нравится дождь за то, что можно быть к тебе ближе под одним зонтом.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я засыпаю и просыпаюсь счастливым с тех пор, как встретил тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Как приятно увидеть принцессу в реальной жизни!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я просто окрылён от счастья быть с тобой.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Когда мы смотрим друг на друга, весь мир для меня словно замирает.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Когда ты рядом, я забываю обо всех своих проблемах.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Рядом с тобой я счастливее с каждым днём.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — воздух для моего огня.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Когда я слышу эту прекрасную песню, я всегда вспоминаю о тебе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Красивее тебя может быть только твоя дочь.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — сама красота.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты безраздельно владеешь моим сердцем.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я восхищаюсь твоим умением находить позитив во всём.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я готов каждый день выбирать только тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — моё пристанище.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я влюбляюсь в тебя каждый раз всё сильнее и сильнее, хоть и кажется, что это уже невозможно.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты выглядишь так великолепно, что я потерял дар речи.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне кажется, что все стихи и песни в мире сложены только о твоей красоте.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне нравится смотреть, как лучики солнца играют в твоих волосах.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне посчастливилось найти клад, о котором я всю жизнь мечтал.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой я чувствую бесконечную гармонию.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я хочу всегда принадлежать тебе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Мне стыдно стоять рядом с тобой, ведь я блекну в сравнении с твоей красотой!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты для меня как все четыре стихии сразу!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твои чарующие глаза притягивают как магниты.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Пусть твоя красота с каждым днём только расцветает!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты мне приснилась, и я понял, как соскучился по тебе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я сегодня проспал. Очень хотел досмотреть сон, в котором ты мне снилась.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Говорят, что красота спасёт мир. Мне кажется, что это именно о твоей красоте.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('У тебя уникальный ум, ты умеешь взглянуть на проблему с разных сторон и быстро её решить.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я готов всегда идти с тобою рядом и делать всё, чтобы ты улыбалась.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Чем чаще ты мне пишешь и звонишь, тем я счастливее.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Один твой взгляд вдохновляет на подвиги!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я хочу, чтобы мы всегда так смотрели друг на друга.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твоя красота вдохновляет на добрые поступки.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твоя улыбка просто обезоруживает.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Когда ты улыбаешься, всё вокруг преображается.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты нужна мне как воздух.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой я просто летаю от счастья.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — мечта, которая стала реальностью.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — моя королева!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты достойна всех комплиментов и восхищений в мире.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я всё время улыбаюсь, потому что не могу скрыть восхищения, глядя на тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я увидел тебя и понял, что ты — мой идеал.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Как тебе удаётся всегда так хорошо выглядеть?') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я уже не помню, как жил без тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты свежа и необходима мне как глоток воздуха.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты так красива, что рядом меркнут звезды.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Чем больше я задумываюсь, какой должна быть идеальная девушка, тем чаще вспоминаю тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я жалею только о том, что не встретил тебя раньше.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я нашёл в тебе всё, что искал.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Хочется любоваться тобой бесконечно.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Встретить в жизни такого человека, как ты, — огромное счастье.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты прекрасна, как самый яркий и красивый цветок.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты каждый раз открываешься для меня с новой прекрасной стороны.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Такой красотой природа наделила только тебя.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('С тобой никогда не бывает скучно.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Даже если очень постараться — найти такую же прекрасную звёздочку, как ты, не получится!') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — образец и пример женского совершенства.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты оставила глубокий след в моей душе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Я непременно должен поблагодарить твоих родителей за то, что они воспитали такого прекрасного человека, как ты.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты делаешь мир ярче одним своим присутствием.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты настоящая загадка, которую я хочу разгадывать снова и снова.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Смело выкладывай свои фотографии, потому что ты всегда выглядишь потрясающе.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твоя красота заставляет мир остановиться и наслаждаться.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — невероятно талантливая и креативная личность.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твои слова всегда находят путь к моему сердцу.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твой смех — самая сладкая мелодия.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты наполнила мой мир красотой и смыслом.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты умеешь создавать магию в повседневных моментах.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты делаешь этот мир добрее.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — словно магия, оживляющая мои серые будни.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Ты — живое напоминание о том, что доброта и красота вечны.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твоя уникальность делает тебя самой прекрасной в мире.') ON CONFLICT (text) DO NOTHING;
INSERT INTO compliments (text) VALUES ('Твои доброта и забота бесценны.') ON CONFLICT (text) DO NOTHING;